// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADG7097jNuvvEB8jllXY5Z-UQtVT9KkgY',
    appId: '1:983678915875:web:ac72b7737c6138bcfa6896',
    messagingSenderId: '983678915875',
    projectId: 'drivoop',
    authDomain: 'drivoop.firebaseapp.com',
    databaseURL: 'https://drivoop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drivoop.appspot.com',
    measurementId: 'G-TPRM2P0GC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUFyIm5XggCnmvnjbCE2q6YksEtb2p1bk',
    appId: '1:983678915875:android:0028ac9825b5e53bfa6896',
    messagingSenderId: '983678915875',
    projectId: 'drivoop',
    databaseURL: 'https://drivoop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drivoop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEqgz5V6qkBde4XHoxgo5CNeATQpkWZA0',
    appId: '1:983678915875:ios:2755e521bc5c810efa6896',
    messagingSenderId: '983678915875',
    projectId: 'drivoop',
    databaseURL: 'https://drivoop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drivoop.appspot.com',
    androidClientId: '983678915875-jrs29tcevudgs6m9024eph96kd7cj6c8.apps.googleusercontent.com',
    iosClientId: '983678915875-fqpqg9lvc85ft4qo6mj0gncf5m6t2b94.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivoolAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEqgz5V6qkBde4XHoxgo5CNeATQpkWZA0',
    appId: '1:983678915875:ios:2755e521bc5c810efa6896',
    messagingSenderId: '983678915875',
    projectId: 'drivoop',
    databaseURL: 'https://drivoop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drivoop.appspot.com',
    androidClientId: '983678915875-jrs29tcevudgs6m9024eph96kd7cj6c8.apps.googleusercontent.com',
    iosClientId: '983678915875-fqpqg9lvc85ft4qo6mj0gncf5m6t2b94.apps.googleusercontent.com',
    iosBundleId: 'com.example.drivoolAssignment',
  );
}
